// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProgettoMeteo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("WeatherRecord", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("City")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("FetchedAt")
                    .HasColumnType("TEXT");

                b.Property<double>("Temperature")
                    .HasColumnType("REAL");

                b.Property<double>("Humidity")
                    .HasColumnType("REAL");

                b.Property<double>("Precipitation")
                    .HasColumnType("REAL");

                b.Property<double>("WindSpeed")
                    .HasColumnType("REAL");

                b.HasKey("Id");

                b.ToTable("WeatherRecords");
            });
#pragma warning restore 612, 618
        }
    }
}